### ISSUE TITLE
Path environment variable, is getting resorted on load

### ISSUE THREAD

**Issue by dalager** [BuriedStPatrick/pwsh#13]
The order of the items in the PATH environment variable matters.

Example: when I have both dotnet x64 and dotnet x86 installed, I need to keep "C:\Program Files\dotnet\dotnet.EXE" first in the path.

I think the path environment var is getting shuffled somehow as it's picking "C:\Program Files (x86)\dotnet" as that has moved up.

To reproduce:
Compare `$ENV:PATH` with or without using pwsh.

**Comment by BuriedStPatrick** [comment]
If the sort order is important, one workaround is to add your paths to the paths-list in `pwsh.yaml`. The reason it's being sorted is due to the fact that `Get-Unique` requires a sorted list to begin with. I use `Get-Unique` to strip any duplicate paths that could've been loaded from other places like the System environment variables and keep `$env:Path` tidy.

If you add `C:\Program Files\dotnet` to your `paths` list in `pwsh.yaml` it will be added at the end of the chain after the Unique-setting has been added. (Probably add quotes around it to be sure).

HOWEVER. It might actually be possible to avoid the whole sorting issue though if we instead use `Select-Object -Unique` which from a brief Google doesn't need the results to be sorted. You're more than welcome to try it out and create a PR :)

[Related code][1]
[Get-Unique docs][2]
[Select-Object -Unique StackOverflow answer][3]

[1]: https://github.com/BuriedStPatrick/pwsh/blob/73cb62837a107fccbc65bee963f8e17127b4233f/pwshrc.ps1#L42
[2]: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-unique?view=powershell-7.2#description
[3]: https://stackoverflow.com/a/26334076

**Comment by dalager** [comment]
Thanks a lot. Might look into that PR-thing :)

**Comment by BuriedStPatrick** [comment]
Merged ✅
